name: walmart-timeseries
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.21.2
  - pandas=1.3.3
  - scikit-learn=0.24.2
  - matplotlib=3.4.3
  - pytorch=1.9.0
  - pip:
    - -r requirements.txt


# Run the following command after creating the environment:
# conda env create -f environment.yml && conda activate walmart-timeseries && conda update -y -n base -c conda-forge conda